# Generated by Django 4.1.7 on 2023-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_id_alter_booking_no_of_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='ModelId',
        ),
        migrations.AlterField(
            model_name='menu',
            name='MenuId',
            field=models.IntegerField(),
        ),
    ]
